Feature #5: Add database files
NeoIsALie/questionsdb pull request #7
Opened 2022-11-08 13:45 UTC by NeoIsALie

2022-11-08 16:26 UTC, negovori requested changes

2022-11-08 16:26 UTC, negovori commented on app/database/init-postgres.sql
> +)
Кажется, чего-то не хватает

2022-11-08 16:26 UTC, negovori commented on app/database/init-postgres.sql
> +    id serial,
Почему не bigserial?

2022-11-08 16:26 UTC, negovori commented on app/database/init-postgres.sql
> +    answer varchar(256) not null,
Не маловато ли для ответа на вопрос?

2022-11-08 16:29 UTC, NeoIsALie commented on app/database/init-postgres.sql
> +)
Да, не хватает самого ключевого слова

2022-11-08 16:51 UTC, negovori requested changes

2022-11-08 16:51 UTC, negovori commented on app/database/init-postgres.sql
> +    kwyword references keywords(id),
Чек мистейк

2022-11-08 16:51 UTC, negovori commented on app/database/init-postgres.sql
> +    id serial,
Ну типа если вопросы у тебя как bigserial числятся, а каждая привязка вопроса к компании будет записью в таблице unification, то как думаешь

2022-11-08 16:51 UTC, negovori commented on app/database/init-postgres.sql
> +    answer varchar(256) not null,
Так может просто varchar?
И что если ответа на вопрос пока нет?

2022-11-10 16:54 UTC, negovori commented
answer просто varchar

2022-11-10 16:57 UTC, negovori commented on app/database/init-postgres.sql
> +    keyword text
А че тут текст и он не имеет "not null"?

2022-11-10 17:05 UTC, NeoIsALie commented on app/database/init-postgres.sql
> +    id serial,
То будет bigserial

2022-11-10 17:17 UTC, NeoIsALie commented on app/database/init-postgres.sql
> +    kwyword references keywords(id),
Исправлю.

2022-11-29 09:47 UTC, negovori commented on app/database/database.py
> +Base = declarative_base()
Возможно стоит перенести в models.py по месту использования

2022-12-27 22:17 UTC, merged